# Generated by Django 4.0.6 on 2022-07-21 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='advert_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='ilana resim ekleyin'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ilan sahibi'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='marka',
            field=models.CharField(max_length=50, verbose_name='ilan markası'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='model',
            field=models.CharField(max_length=50, verbose_name='ilan modeli'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='price',
            field=models.CharField(max_length=50, verbose_name='ilan fiyatı'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='title',
            field=models.CharField(max_length=50, verbose_name='ilan başlığı'),
        ),
    ]
